/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e215726;

public class Main {
    public static void main(String[] args) {
        GameMaster master = new GameMaster();
        master.init();
        master.start();
    }
}